### ISSUE TITLE
After running the code Im getting value as 35.62. The original paper reports values in decimals like 0.82 etc. Are they both right?

### ISSUE THREAD

**Issue by AdarshMJ** [paulwong16/UCIQE#2]

**Comment by shouvik-paul** [comment]
@AdarshMJ yes, you are right. I am facing same problem. UCIQE value is in between (0-1). But it shows 14.5, 15.8, 17.9, 35.23 etc. Any suggestion @paulwong16 ?

**Comment by paulwong16** [comment]
> @AdarshMJ yes, you are right. I am facing same problem. UCIQE value is in between (0-1). But it shows 14.5, 15.8, 17.9, 35.23 etc. Any suggestion @paulwong16 ?

Hi, I'm not sure if the original paper did normlization on lab color value. For the calculation of values in eq14, pls refer to _Measuring colourfulness in natural images_. For converting rgb to lab, pls refer to the book _mesearuing color_. FYI, the code I used for converting rgb to lab [http://ai.stanford.edu/~ruzon/software/rgblab.html](url)

**Comment by lee2430** [comment]
For anyone who needs, I found another implimentation of UCIQE at:
[bilityniu/underimage-fusion-enhancement](https://github.com/bilityniu/underimage-fusion-enhancement/blob/master/UCIQE.m)
