### ISSUE TITLE
Getting values as 14.5, 15.8, 17.9, 35.23 etc. not 0.56,0.45 etc.

### ISSUE THREAD

**Issue by shouvik-paul** [paulwong16/UCIQE#3]
UCIQE value is in between (0-1). But it shows 14.5, 15.8, 17.9, 35.23 etc. Any suggestion @paulwong16 ?

**Comment by paulwong16** [comment]
Refer to [this link](https://github.com/paulwong16/UCIQE/issues/2#issuecomment-654290102)

> UCIQE value is in between (0-1). But it shows 14.5, 15.8, 17.9, 35.23 etc. Any suggestion @paulwong16 ?
